<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CarRental.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="ClientsForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="TransactionsForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\Cars\CarsDeleteForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\Cars\CarsForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\Cars\CarAddForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\Cars\AddOurOrWhose.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>

</Project>